### ISSUE TITLE
problems with soundbanks and announcer calls

### ISSUE THREAD

**Issue by relentlessb** [squidgy617/BrawlInstallerPlugins#88] opened 2023-03-10 06:55 UTC
After extracting some characters from other P+ builds, I tried to install them on my own build but came up with many issues when it came to transferring the soundbanks accurately to my build. It seems that some moves are accurate but many moves and the announcer calls are missing or wrong. Is there any way to fix this?

**Comment by squidgy617** [comment] 2023-03-10 13:39
Announcer calls are not based on fighter soundbanks and are not supported by BrawlInstaller currently. If you wish to use custom announcer calls for your fighter, you must configure those manually. This is because announcer calls can't be added to the game currently - they can only replace existing sounds.

For sounds missing from fighter moves, most likely your build settings regarding soundbanks are wrong. Make sure to verify those settings are configured correctly for your build.

**Comment by relentlessb** [comment] 2023-03-10 22:13
Thanks for the info on the announcer calls,

Ill get back to you on the build settings. I'm using a fresh P+EX build and am using the P+ build settings. Is there any way I should change the build P+ settings to be adjusted for P+EX?

**Comment by squidgy617** [comment] 2023-03-10 22:35
Well it sounds like the correct settings to me, so I'm not sure what's causing your soundbank issues. What characters are you specifically having issues with?

**Comment by relentlessb** [comment] 2023-03-11 01:57
[Goku.zip](https://github.com/squidgy617/BrawlInstallerPlugins/files/10947315/Goku.zip)

I was using this file, and I've verified that the soundbank contained works and has all the sounds on it.

**Comment by squidgy617** [comment] 2023-03-12 01:54
If this issue only occurs with the fighter package you posted (and possibly other fighters you extracted), then the problem is with either the character itself, the settings you used when extracting the character, or the build you extracted from. When extracting characters, make sure the soundbank settings are configured correctly for the build you're extracting from (I don't know what build Goku is in).

If this problem also occurs when installing other packages (such as the ones here: http://forums.kc-mm.com/Gallery/BrawlView.php?ByUserID=28848&Moderated=All), then I'm not sure what the issue is.

**Comment by squidgy617** [comment] 2023-03-21 03:09
Closing this as it does not appear to be an issue with the plugins, but feel free to reopen or create a new issue if a problem with the plugins is confirmed.

**Closed by squidgy617** 2023-03-21 03:09 UTC
